export const perfumeList = [
  {
    id: "perfume1",
    name: "perfume1",
    description: "description",
    gender: "",
    notes: "",
    tag: "",
    addedBy: "",
  },
  {
    id: "perfume2",
    name: "perfume2",
    description: "description2",
    gender: "",
    notes: "",
    tag: "",
    addedBy: "",
  },
  {
    id: "perfume3",
    name: "perfume3",
    description: "description3",
    gender: "",
    notes: "",
    tag: "",
    addedBy: "",
  },
  {
    id: "perfume4",
    name: "perfume4",
    description: "perfume4",
    gender: "",
    notes: "",
    tag: "",
    addedBy: "",
  },
  {
    id: "perfume5",
    name: "perfume5",
    description: "perfume5",
    gender: "",
    notes: "",
    tag: "",
    addedBy: "",
  },
  {
    id: "perfume6",
    name: "perfume6",
    description: "perfume6",
    gender: "",
    notes: "",
    tag: "",
    addedBy: "",
  },
];
